# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Mod Properties
mod_id=omnisearch
mod_name=Omnisearch
mod_license=MIT
mod_version=2.0.0
mod_group_id=com.cy311.omnisearch
mod_authors=cy311
mod_description=Search and browse mcmod.cn in-game
